//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionesEmpleados
    {
        public int id { get; set; }
        public string tipoModificacion { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> avionId { get; set; }
        public Nullable<int> vueloId { get; set; }
        public string abreviaturaAeropuerto { get; set; }
        public string docEmpleado { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Avion Avion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
