//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccionesEmpleados
    {
        public int id { get; set; }
        public string tipoModificacion { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> avionId { get; set; }
        public Nullable<int> vueloId { get; set; }
        public string abreviaturaAeropuerto { get; set; }
        public string docEmpleado { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Avion Avion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
