//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Pasaje = new HashSet<Pasaje>();
        }
    
        public int idCompra { get; set; }
        public System.DateTime fechaCompra { get; set; }
        public string nombreTitular { get; set; }
        public string apellidoTitular { get; set; }
        public string documentoTitular { get; set; }
        public string tipoTarjeta { get; set; }
        public string companiaTarjeta { get; set; }
        public int numeroTarjeta { get; set; }
        public Nullable<System.DateTime> vencimientoTarjeta { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasaje> Pasaje { get; set; }
    }
}
