//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoTasa
    {
        public int idTasa { get; set; }
        public System.DateTime fecha { get; set; }
        public double tasaRegional { get; set; }
        public double tasaIntercontinental { get; set; }
        public string codigoAirport { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
    }
}
