//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasaje
    {
        public int idPasaje { get; set; }
        public string nombrePasajero { get; set; }
        public string apellidoPasajero { get; set; }
        public string documentoPasajero { get; set; }
        public int vueloId { get; set; }
        public int compraId { get; set; }
        public int asientoNumero { get; set; }
        public int avionId { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
