//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasaje
    {
        public int idPasaje { get; set; }
        public string nombrePasajero { get; set; }
        public string apellidoPasajero { get; set; }
        public string documentoPasajero { get; set; }
        public int vueloId { get; set; }
        public int compraId { get; set; }
        public int asientoNumero { get; set; }
        public int avionId { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
