//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioCategoria
    {
        public double precioEconomy { get; set; }
        public double precioPremium { get; set; }
        public double precioBusiness { get; set; }
        public double precioFirstClass { get; set; }
        public int avionId { get; set; }
        public int vueloId { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
