//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelo()
        {
            this.AccionesEmpleados = new HashSet<AccionesEmpleados>();
            this.Pasaje = new HashSet<Pasaje>();
        }
    
        public int idVuelo { get; set; }
        public string numeroVuelo { get; set; }
        public System.DateTime fechaSalida { get; set; }
        public System.DateTime fechaLlegada { get; set; }
        public double horasVuelo { get; set; }
        public string estado { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
        public int avionId { get; set; }
        public string tipo { get; set; }
        public string visa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccionesEmpleados> AccionesEmpleados { get; set; }
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Aeropuerto Aeropuerto1 { get; set; }
        public virtual Avion Avion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasaje> Pasaje { get; set; }
        public virtual PrecioCategoria PrecioCategoria { get; set; }
    }
}
